### ISSUE TITLE
Broken link in article

### ISSUE THREAD

**Issue by gabriel-aizcorbe** [tarwn/lessthandot-hugo#2]
Hi, I was reading the following article
https://blogs.lessthandot.com/index.php/datamgmt/datadesign/find-out-if-you-are-using-deprecated-fea-2008/

and there is a reference to another article 
"..._You can also take a look at these blog posts by [George Mastros](https://blogs.lessthandot.com/index.php/All/?disp=authdir&author=10) that show you how you can find out where some of this stuff is called from_..."  (George Mastros is the hyperlink to this URL : https://blogs.lessthandot.com/index.php/All/?disp=authdir&author=10 )  but the article seems to be lost

Any chance to restore it ?

Thanks
Gabriel

**Comment by tarwn** [comment]
Sorry, I never received a notification on your issue. I'm sure since it's  been a few years you've since forgotten what you were looking for (or otherwise found it). But, if you're still looking for posts by George, this link lists his full post history: https://blogs.lessthandot.com/author/george-mastros-gmmastros
